services:
  nginx:
    build: 
      context: .
      args:
        - EMAIL=${EMAIL}
        - DOMAIN=${DOMAIN}
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
